@echo off
REM Build VOK for Windows and create a full installer (.exe) with welcome and license.
REM Run from project root: scripts\build_win_installer.bat
REM
REM Requires Inno Setup 6: https://jrsoftware.org/isinfo.php
REM   Auto-detected at default install locations. Override with:
REM     set ISCC_PATH=C:\path\to\ISCC.exe
REM
REM Optional code signing (for distribution):
REM   set SIGN_CERT_FILE=C:\path\to\cert.pfx
REM   set SIGN_CERT_PASSWORD=yourpassword
REM   set SIGN_TIMESTAMP_URL=http://timestamp.digicert.com  (optional, defaults to DigiCert)

setlocal enabledelayedexpansion
cd /d "%~dp0\.."

echo ========================================
echo   VOK -- Build Windows installer (.exe)
echo ========================================

REM ── Build the app first if needed ────────────────────────────────────────────
if not exist "dist\VOK\VOK.exe" (
    echo Building app...
    echo Syncing dev dependencies...
    uv sync --extra dev
    if errorlevel 1 ( echo ERROR: uv sync failed. & exit /b 1 )

    echo Building with PyInstaller...
    uv run pyinstaller vok.spec --clean --noconfirm
    if errorlevel 1 ( echo ERROR: PyInstaller build failed. & exit /b 1 )
) else (
    echo Using existing dist\VOK\VOK.exe ^(delete it to force rebuild^).
)

if not exist "dist\VOK\VOK.exe" (
    echo ERROR: dist\VOK\VOK.exe not found after build.
    exit /b 1
)

REM ── Read version from pyproject.toml ─────────────────────────────────────────
set "VERSION=0.1.0"
for /f "tokens=3" %%v in ('findstr /r "^version " pyproject.toml') do set "VERSION=%%v"
set "VERSION=%VERSION:"=%"
echo Version: %VERSION%

REM ── Locate ISCC.exe (Inno Setup compiler) ────────────────────────────────────
set "ISCC="
if defined ISCC_PATH (
    set "ISCC=%ISCC_PATH%"
) else (
    if exist "C:\Program Files (x86)\Inno Setup 6\ISCC.exe" set "ISCC=C:\Program Files (x86)\Inno Setup 6\ISCC.exe"
    if exist "C:\Program Files\Inno Setup 6\ISCC.exe"       set "ISCC=C:\Program Files\Inno Setup 6\ISCC.exe"
    if exist "C:\Program Files (x86)\Inno Setup 5\ISCC.exe" set "ISCC=C:\Program Files (x86)\Inno Setup 5\ISCC.exe"
    if exist "C:\Program Files\Inno Setup 5\ISCC.exe"       set "ISCC=C:\Program Files\Inno Setup 5\ISCC.exe"
)

if "%ISCC%"=="" (
    echo.
    echo ERROR: Inno Setup not found.
    echo   Install it from: https://jrsoftware.org/isinfo.php
    echo   Or set ISCC_PATH to the full path of ISCC.exe
    exit /b 1
)
echo Using Inno Setup: %ISCC%

REM ── Generate Inno Setup script (.iss) ────────────────────────────────────────
REM Use absolute paths so Inno Setup resolves files from the project root,
REM not from the .iss file's location inside dist\.
set "ROOT=%CD%"
set "ISS_FILE=%ROOT%\dist\VOK-installer.iss"
set "OUTPUT_FILENAME=VOK-Install-%VERSION%"
set "ICON_FLAG="
if exist "%ROOT%\resources\icon.ico" set "ICON_FLAG=SetupIconFile=%ROOT%\resources\icon.ico"

echo.
echo Generating installer script...

(
echo ; VOK Windows Installer Script
echo ; Auto-generated by build_win_installer.bat -- do not edit manually.
echo.
echo [Setup]
echo AppName=VOK
echo AppVersion=%VERSION%
echo AppPublisher=VOK
echo AppPublisherURL=https://github.com/vok/vok
echo AppSupportURL=https://github.com/vok/vok/issues
echo DefaultDirName={autopf}\VOK
echo DefaultGroupName=VOK
echo DisableProgramGroupPage=yes
echo OutputDir=%ROOT%\dist
echo OutputBaseFilename=%OUTPUT_FILENAME%
echo Compression=lzma
echo SolidCompression=yes
echo WizardStyle=modern
echo LicenseFile=%ROOT%\resources\installer\license.rtf
echo InfoBeforeFile=%ROOT%\resources\installer\welcome_win.txt
echo UninstallDisplayIcon={app}\VOK.exe
echo PrivilegesRequired=admin
echo ArchitecturesInstallIn64BitMode=x64
) > "%ISS_FILE%"

if defined ICON_FLAG (
    echo %ICON_FLAG% >> "%ISS_FILE%"
)

(
echo.
echo [Languages]
echo Name: "english"; MessagesFile: "compiler:Default.isl"
echo.
echo [Tasks]
echo Name: "desktopicon"; Description: "{cm:CreateDesktopIcon}"; GroupDescription: "{cm:AdditionalIcons}"; Flags: unchecked
echo.
echo [Files]
echo Source: "%ROOT%\dist\VOK\*"; DestDir: "{app}"; Flags: ignoreversion recursesubdirs createallsubdirs
echo.
echo [Icons]
echo Name: "{group}\VOK"; Filename: "{app}\VOK.exe"
echo Name: "{group}\Uninstall VOK"; Filename: "{uninstallexe}"
echo Name: "{autodesktop}\VOK"; Filename: "{app}\VOK.exe"; Tasks: desktopicon
echo.
echo [Run]
echo Filename: "{app}\VOK.exe"; Description: "{cm:LaunchProgram,VOK}"; Flags: nowait postinstall skipifsilent
) >> "%ISS_FILE%"

REM ── Compile the installer ─────────────────────────────────────────────────────
echo Compiling installer...
"%ISCC%" "%ISS_FILE%"
if errorlevel 1 (
    echo ERROR: Inno Setup compilation failed.
    del /f /q "%ISS_FILE%" 2>nul
    exit /b 1
)

del /f /q "%ISS_FILE%" 2>nul

REM ── Optional: code-sign the installer ────────────────────────────────────────
if defined SIGN_CERT_FILE (
    echo Signing installer...
    set "TS_URL=%SIGN_TIMESTAMP_URL%"
    if not defined TS_URL set "TS_URL=http://timestamp.digicert.com"

    where signtool >nul 2>&1
    if errorlevel 1 (
        echo WARNING: signtool.exe not found -- skipping signing.
        echo   Run from a Developer Command Prompt or add Windows SDK to PATH.
    ) else (
        signtool sign /f "%SIGN_CERT_FILE%" /p "%SIGN_CERT_PASSWORD%" /t "!TS_URL!" /d "VOK" "%ROOT%\dist\%OUTPUT_FILENAME%.exe"
        if errorlevel 1 (
            echo ERROR: Code signing failed.
            exit /b 1
        )
        echo Signing complete.
    )
)

echo.
echo ========================================
echo   Installer created: dist\%OUTPUT_FILENAME%.exe
echo ========================================
echo.
echo Users can double-click the .exe to see the welcome and license, then install VOK.

pause
