@echo off
REM Build VOK for Windows and create a full installer (.exe) with welcome and license.
REM Run from project root: scripts\build_win_installer.bat
REM
REM Requires Inno Setup 6: https://jrsoftware.org/isinfo.php
REM   Auto-detected at default install locations. Override with:
REM     set ISCC_PATH=C:\path\to\ISCC.exe
REM
REM Optional code signing (for distribution):
REM   set SIGN_CERT_FILE=C:\path\to\cert.pfx
REM   set SIGN_CERT_PASSWORD=yourpassword
REM   set SIGN_TIMESTAMP_URL=http://timestamp.digicert.com  (optional, defaults to DigiCert)

setlocal enabledelayedexpansion
cd /d "%~dp0\.."

echo ========================================
echo   VOK -- Build Windows installer (.exe)
echo ========================================

REM ── Clean previous build so every run is a fresh build ────────────────────────
if exist "dist\VOK" (
    echo Removing previous build: dist\VOK
    rmdir /s /q "dist\VOK"
)
if exist "build\vok" (
    echo Removing previous build cache: build\vok
    rmdir /s /q "build\vok"
)

REM ── Build the app ────────────────────────────────────────────────────────────
echo Building app...
echo Syncing dev dependencies...
uv sync --extra dev
if errorlevel 1 ( echo ERROR: uv sync failed. & exit /b 1 )

echo Building with PyInstaller...
uv run pyinstaller vok.spec --clean --noconfirm
if errorlevel 1 ( echo ERROR: PyInstaller build failed. & exit /b 1 )

if not exist "dist\VOK\VOK.exe" (
    echo ERROR: dist\VOK\VOK.exe not found after build.
    exit /b 1
)

REM ── Read version from pyproject.toml ─────────────────────────────────────────
set "VERSION=0.1.0"
for /f "tokens=3" %%v in ('findstr /r "^version " pyproject.toml') do set "VERSION=%%v"
set "VERSION=%VERSION:"=%"
echo Version: %VERSION%

REM ── Locate ISCC.exe (Inno Setup compiler) ────────────────────────────────────
REM Avoid ( ) blocks with paths containing (x86) or text containing "install" to prevent parse errors.
set "ISCC="
if defined ISCC_PATH set "ISCC=%ISCC_PATH%"
if "%ISCC%"=="" if exist "C:\Program Files (x86)\Inno Setup 6\ISCC.exe" set "ISCC=C:\Program Files (x86)\Inno Setup 6\ISCC.exe"
if "%ISCC%"=="" if exist "C:\Program Files\Inno Setup 6\ISCC.exe" set "ISCC=C:\Program Files\Inno Setup 6\ISCC.exe"
if "%ISCC%"=="" if exist "C:\Program Files (x86)\Inno Setup 5\ISCC.exe" set "ISCC=C:\Program Files (x86)\Inno Setup 5\ISCC.exe"
if "%ISCC%"=="" if exist "C:\Program Files\Inno Setup 5\ISCC.exe" set "ISCC=C:\Program Files\Inno Setup 5\ISCC.exe"

if "%ISCC%"=="" goto :no_iscc
echo Using Inno Setup: %ISCC%
goto :after_iscc_check
:no_iscc
echo.
echo WARNING: Inno Setup not found - skipping installer step.
echo   Application built successfully: dist\VOK\VOK.exe
echo   To create the full installer, get Inno Setup from:
echo     https://jrsoftware.org/isinfo.php
echo   Or set ISCC_PATH to the full path of ISCC.exe and re-run this script.
echo.
goto :build_done
:after_iscc_check

REM ── Generate Inno Setup script (.iss) ────────────────────────────────────────
REM Use absolute paths so Inno Setup resolves files from the project root,
REM not from the .iss file's location inside dist\.
set "ROOT=%CD%"
set "ISS_FILE=%ROOT%\dist\VOK-installer.iss"
set "OUTPUT_FILENAME=VOK-Install-%VERSION%"
set "ICON_FLAG="
if exist "%ROOT%\resources\icon.ico" set "ICON_FLAG=SetupIconFile=%ROOT%\resources\icon.ico"

echo.
echo Generating installer script...

REM Write .iss in parts to avoid "install" parse errors inside ( ) blocks
> "%ISS_FILE%" echo ; VOK Windows Installer Script
>> "%ISS_FILE%" echo ; Auto-generated by build_win_installer.bat -- do not edit manually.
>> "%ISS_FILE%" echo.
>> "%ISS_FILE%" echo [Setup]
>> "%ISS_FILE%" echo AppName=VOK
>> "%ISS_FILE%" echo AppVersion=%VERSION%
>> "%ISS_FILE%" echo AppPublisher=VOK
>> "%ISS_FILE%" echo AppPublisherURL=https://github.com/vok/vok
>> "%ISS_FILE%" echo AppSupportURL=https://github.com/vok/vok/issues
>> "%ISS_FILE%" echo AppUpdatesURL=https://github.com/vok/vok/releases
>> "%ISS_FILE%" echo AppId={{D8F8B5E2-3F4C-4A2A-9A6D-E1B2C3D4E5F6}}
>> "%ISS_FILE%" echo DefaultDirName={autopf}\VOK
>> "%ISS_FILE%" echo DefaultGroupName=VOK
>> "%ISS_FILE%" echo DisableProgramGroupPage=yes
>> "%ISS_FILE%" echo OutputDir=%ROOT%\dist
>> "%ISS_FILE%" echo OutputBaseFilename=%OUTPUT_FILENAME%
>> "%ISS_FILE%" echo Compression=lzma
>> "%ISS_FILE%" echo SolidCompression=yes
>> "%ISS_FILE%" echo WizardStyle=modern
>> "%ISS_FILE%" echo LicenseFile=%ROOT%\resources\installer\license.rtf
>> "%ISS_FILE%" echo InfoBeforeFile=%ROOT%\resources\installer\welcome_win.txt
>> "%ISS_FILE%" echo UninstallDisplayIcon={app}\VOK.exe
>> "%ISS_FILE%" echo PrivilegesRequired=admin
>> "%ISS_FILE%" echo ArchitecturesInstallIn64BitMode=x64
>> "%ISS_FILE%" echo AppMutex=VOK_MUTEX
>> "%ISS_FILE%" echo CloseApplications=yes
>> "%ISS_FILE%" echo RestartApplications=no
>> "%ISS_FILE%" echo VersionInfoVersion=%VERSION%
>> "%ISS_FILE%" echo VersionInfoCompany=VOK
>> "%ISS_FILE%" echo VersionInfoDescription=VOK Application
>> "%ISS_FILE%" echo VersionInfoProductName=VOK

if defined ICON_FLAG (
    echo %ICON_FLAG% >> "%ISS_FILE%"
)

>> "%ISS_FILE%" echo.
>> "%ISS_FILE%" echo [Languages]
>> "%ISS_FILE%" echo Name: "english"; MessagesFile: "compiler:Default.isl"
>> "%ISS_FILE%" echo.
>> "%ISS_FILE%" echo [Tasks]
>> "%ISS_FILE%" echo Name: "desktopicon"; Description: "{cm:CreateDesktopIcon}"; GroupDescription: "{cm:AdditionalIcons}"; Flags: unchecked
>> "%ISS_FILE%" echo.
>> "%ISS_FILE%" echo [Files]
>> "%ISS_FILE%" echo Source: "%ROOT%\dist\VOK\*"; DestDir: "{app}"; Flags: ignoreversion recursesubdirs createallsubdirs
>> "%ISS_FILE%" echo.
>> "%ISS_FILE%" echo [Icons]
>> "%ISS_FILE%" echo Name: "{group}\VOK"; Filename: "{app}\VOK.exe"
>> "%ISS_FILE%" echo Name: "{group}\Uninstall VOK"; Filename: "{uninstallexe}"
>> "%ISS_FILE%" echo Name: "{autodesktop}\VOK"; Filename: "{app}\VOK.exe"; Tasks: desktopicon
>> "%ISS_FILE%" echo.
>> "%ISS_FILE%" echo [Run]
>> "%ISS_FILE%" echo Filename: "{app}\VOK.exe"; Description: "{cm:LaunchProgram,VOK}"; Flags: nowait postinstall skipifsilent

REM ── Compile the installer ─────────────────────────────────────────────────────
echo Compiling installer...
"%ISCC%" "%ISS_FILE%"
if errorlevel 1 (
    echo ERROR: Inno Setup compilation failed.
    del /f /q "%ISS_FILE%" 2>nul
    exit /b 1
)

del /f /q "%ISS_FILE%" 2>nul

REM ── Optional: code-sign the installer ────────────────────────────────────────
if defined SIGN_CERT_FILE (
    echo Signing installer...
    set "TS_URL=%SIGN_TIMESTAMP_URL%"
    if not defined TS_URL set "TS_URL=http://timestamp.digicert.com"

    where signtool >nul 2>&1
    if errorlevel 1 (
        echo WARNING: signtool.exe not found -- skipping signing.
        echo   Run from a Developer Command Prompt or add Windows SDK to PATH.
    ) else (
        signtool sign /f "%SIGN_CERT_FILE%" /p "%SIGN_CERT_PASSWORD%" /t "!TS_URL!" /d "VOK" "%ROOT%\dist\%OUTPUT_FILENAME%.exe"
        if errorlevel 1 (
            echo ERROR: Code signing failed.
            exit /b 1
        )
        echo Signing complete.
    )
)

echo.
echo ========================================
echo   Installer created: dist\%OUTPUT_FILENAME%.exe
echo ========================================
echo.
echo Users can double-click the .exe to see the welcome and license, then install VOK.

:build_done
echo.
echo Application EXE: dist\VOK\VOK.exe
echo Run it directly or build the installer with Inno Setup for a setup wizard.
echo.

pause
