name: Build Linux

on:
  workflow_dispatch:

jobs:
  build-ubuntu:
    strategy:
      matrix:
        architecture: [x86_64, arm64]
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python 3.11
        uses: actions/setup-python@v4
        with:
          python-version: '3.12'

      - name: Configure Git for private repo access
        if: ${{ secrets.GH_PAT != '' }}
        run: |
          git config --global url."https://x-access-token:${{ secrets.GH_PAT }}@github.com/".insteadOf "https://github.com/"

      - name: Install dependencies
        run: |
          pip install -r requirements.txt

      - name: Build with PyInstaller
        run: |
          VERSION=$(python3 -c "from app.common.setting import VERSION; print(VERSION)")
          echo "VERSION=${VERSION}" >> $GITHUB_ENV
          

      - name: Download and extract tools
        run: |
          # Setup variables
          ZIP_URL="https://github.com/VOK-KH/VOK-Get/releases/download/v0.2.0/Linux-${{ matrix.architecture }}.zip"
          DEST_DIR="dist/VOK-Get/_internal/tools"

          # Download tools
          echo "Downloading package from $ZIP_URL..."
          curl -L "$ZIP_URL" -o "/tmp/package.zip"

          # unzip
          echo "Extracting package..."
          unzip -o "/tmp/package.zip" -d "$DEST_DIR"

          # delete zip
          rm "/tmp/package.zip"

          echo "Download and extraction complete!"

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: VOK-Get-v${{ env.VERSION }}-Linux-${{ matrix.architecture }}
          path: dist/VOK-Get
