name: Release

on:
  release:
    types: [published]

jobs:
  build-windows:
    strategy:
      matrix:
        architecture: [x86_64]
    runs-on: windows-2019
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python 3.11
        uses: actions/setup-python@v4
        with:
          python-version: '3.12'

      - name: Configure Git for private repo access
        if: ${{ secrets.GH_PAT != '' }}
        run: git config --global url."https://x-access-token:${{ secrets.GH_PAT }}@github.com/".insteadOf "https://github.com/"

      - name: Install dependencies
        run: |
          pip install -r requirements.txt

      - name: Build with Nuitka
        run: |
          

      - name: Download and extract tools
        shell: pwsh
        run: |
          # Setup variables
          $ZIP_URL = "https://github.com/VOK-KH/VOK-Get/releases/download/v0.2.0/Windows-${{ matrix.architecture }}.zip"
          $DEST_DIR = "dist/VOK-Get.dist/tools"

          # download zip
          Write-Output "Downloading package from $ZIP_URL..."
          Invoke-WebRequest -Uri $ZIP_URL -OutFile "$env:TEMP/package.zip"

          # unzip
          Write-Output "Extracting package..."
          Expand-Archive -Path "$env:TEMP/package.zip" -DestinationPath $DEST_DIR -Force

          # delete zip
          Remove-Item "$env:TEMP/package.zip" -Force

          Write-Output "Download and extraction complete!"

      - name: Create zip file
        shell: pwsh
        run: |
          $VERSION = python -c "from app.common.setting import VERSION; print(VERSION)"
          Write-Host "VERSION=$VERSION"
          echo "VERSION=$VERSION" >> $env:GITHUB_ENV

          $distPath = "dist/VOK-Get.dist"
          $zipFile = "VOK-Get-v$VERSION-Windows-${{ matrix.architecture }}.zip"

          # Create a zip file containing the contents of VOK-Get.dist, without the folder itself
          Write-Output "Zipping contents of $distPath..."
          Compress-Archive -Path "$distPath\*" -DestinationPath $zipFile
          Write-Output "Zip created at $zipFile"

      - name: Download Inno Setup Translation Files
        run: |
          Invoke-WebRequest -Uri "https://raw.githubusercontent.com/jrsoftware/issrc/main/Files/Languages/Unofficial/ChineseSimplified.isl" -OutFile "C:\Program Files (x86)\Inno Setup 6\Languages\ChineseSimplified.isl"

      - name: Build Installer
        uses: Minionguyjpro/Inno-Setup-Action@v1.2.5
        with:
          path: VOK-Get.iss

      - name: Upload to release
        uses: softprops/action-gh-release@v2
        if: github.event_name == 'release'
        with:
          tag_name: ${{ github.event.release.tag_name }}
          files: |
            VOK-Get-v${{ env.VERSION }}-Windows-${{ matrix.architecture }}.zip
            dist/VOK-Get-v${{ env.VERSION }}-Windows-${{ matrix.architecture }}-Setup.exe

  build-macos-14-arm:
    strategy:
      fail-fast: false
      matrix:
        architecture: [arm64]
    runs-on: macos-14
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python 3.11
        uses: actions/setup-python@v4
        with:
          python-version: '3.12'

      - name: Configure Git for private repo access
        if: ${{ secrets.GH_PAT != '' }}
        run: |
          git config --global url."https://x-access-token:${{ secrets.GH_PAT }}@github.com/".insteadOf "https://github.com/"

      - name: Install dependencies
        run: |
          pip install -r requirements.txt

      - name: Build with Nuitka
        run: |
          VERSION=$(python3 -c "from app.common.setting import VERSION; print(VERSION)")
          echo "VERSION=${VERSION}" >> $GITHUB_ENV
          
          chmod u+x "dist/VOK-Get.app/Contents/MacOS/VOK-Get"
          rm -rf "dist/VOK-Get.build"

      - name: Download and extract tools
        run: |
          # Setup variables
          ZIP_URL="https://github.com/VOK-KH/VOK-Get/releases/download/v0.2.0/macOS-${{ matrix.architecture }}.zip"
          DEST_DIR="dist/VOK-Get.app/Contents/MacOS/tools"

          # Download tools
          echo "Downloading package from $ZIP_URL..."
          curl -L "$ZIP_URL" -o "/tmp/package.zip"

          # unzip
          echo "Extracting package..."
          unzip -o "/tmp/package.zip" -d "$DEST_DIR"

          # delete zip
          rm "/tmp/package.zip"

          echo "Download and extraction complete!"

      - name: Create DMG
        run: |
          ln -s /Applications dist/Applications

          attempt=0
          max_attempts=10
          while [ $attempt -lt $max_attempts ]; do
              hdiutil create -srcfolder "dist/" -volname "VOK-Get" -fs HFS+ \
                  -fsargs "-c c=64,a=16,e=16" -format UDZO -size 400m \
                  "VOK-Get-v${{ env.VERSION }}-macOS-${{ matrix.architecture }}.dmg" && break

              attempt=$((attempt + 1))
              echo "Attempt $attempt failed, retrying..."
              sleep 1  # 等待 1 秒后重试
          done

          if [ $attempt -eq $max_attempts ]; then
              echo "Failed to create DMG after $max_attempts attempts"
              exit 1
          fi

      - name: Upload to release
        uses: softprops/action-gh-release@v2
        if: github.event_name == 'release'
        with:
          tag_name: ${{ github.event.release.tag_name }}
          files: VOK-Get-v${{ env.VERSION }}-macOS-${{ matrix.architecture }}.dmg

  build-macos-x86_64:
    strategy:
      matrix:
        architecture: [x86_64]
    runs-on: macos-15-intel
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Remove problematic brew libs
        run: |
          brew remove --force --ignore-dependencies openssl@3
          brew cleanup openssl@3

      - name: Set up Python 3.11
        uses: actions/setup-python@v4
        with:
          python-version: '3.12'

      - name: Configure Git for private repo access
        if: ${{ secrets.GH_PAT != '' }}
        run: |
          git config --global url."https://x-access-token:${{ secrets.GH_PAT }}@github.com/".insteadOf "https://github.com/"

      - name: Install dependencies
        run: |
          pip install -r requirements.txt

      - name: Build with Nuitka
        run: |
          VERSION=$(python3 -c "from app.common.setting import VERSION; print(VERSION)")
          echo "VERSION=${VERSION}" >> $GITHUB_ENV
          
          chmod u+x "dist/VOK-Get.app/Contents/MacOS/VOK-Get"
          rm -rf "dist/VOK-Get.build"

      - name: Reinstall openssl libs
        run: |
          brew install openssl@3

      - name: Download and extract tools
        run: |
          # Setup variables
          ZIP_URL="https://github.com/VOK-KH/VOK-Get/releases/download/v0.2.0/macOS-${{ matrix.architecture }}.zip"
          DEST_DIR="dist/VOK-Get.app/Contents/MacOS/tools"

          # Download tools
          echo "Downloading package from $ZIP_URL..."
          curl -L "$ZIP_URL" -o "/tmp/package.zip"

          # unzip
          echo "Extracting package..."
          unzip -o "/tmp/package.zip" -d "$DEST_DIR"

          # delete zip
          rm "/tmp/package.zip"

          echo "Download and extraction complete!"

      - name: Create DMG
        run: |
          ln -s /Applications dist/Applications
          hdiutil create -srcfolder "dist/" -volname "VOK-Get" -fs HFS+ -fsargs "-c c=64,a=16,e=16" -format UDZO -size 400m "VOK-Get-v${{ env.VERSION }}-macOS-${{ matrix.architecture }}.dmg"

      - name: Upload to release
        uses: softprops/action-gh-release@v2
        if: github.event_name == 'release'
        with:
          tag_name: ${{ github.event.release.tag_name }}
          files: VOK-Get-v${{ env.VERSION }}-macOS-${{ matrix.architecture }}.dmg

  build-ubuntu:
    strategy:
      matrix:
        architecture: [x86_64, arm64]
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python 3.11
        uses: actions/setup-python@v4
        with:
          python-version: '3.12'

      - name: Configure Git for private repo access
        if: ${{ secrets.GH_PAT != '' }}
        run: |
          git config --global url."https://x-access-token:${{ secrets.GH_PAT }}@github.com/".insteadOf "https://github.com/"

      - name: Install dependencies
        run: |
          pip install -r requirements.txt

      - name: Build with PyInstaller
        run: |
          VERSION=$(python3 -c "from app.common.setting import VERSION; print(VERSION)")
          echo "VERSION=${VERSION}" >> $GITHUB_ENV
          

      - name: Download and extract tools
        run: |
          # Setup variables
          ZIP_URL="https://github.com/VOK-KH/VOK-Get/releases/download/v0.2.0/Linux-${{ matrix.architecture }}.zip"
          DEST_DIR="dist/VOK-Get/_internal/tools"

          # Download tools
          echo "Downloading package from $ZIP_URL..."
          curl -L "$ZIP_URL" -o "/tmp/package.zip"

          # unzip
          echo "Extracting package..."
          unzip -o "/tmp/package.zip" -d "$DEST_DIR"

          # delete zip
          rm "/tmp/package.zip"

          echo "Download and extraction complete!"

      - name: Zip the contents of VOK-Get
        shell: pwsh
        run: |
          $distPath = "dist/VOK-Get"
          $zipFile = "VOK-Get-v${{ env.VERSION }}-Linux-${{ matrix.architecture }}.zip"

          # Create a zip file containing the contents of VOK-Get.dist, without the folder itself
          Write-Output "Zipping contents of $distPath..."
          Compress-Archive -Path "$distPath\*" -DestinationPath $zipFile
          Write-Output "Zip created at $zipFile"

      - name: Upload to release
        uses: softprops/action-gh-release@v2
        if: github.event_name == 'release'
        with:
          tag_name: ${{ github.event.release.tag_name }}
          files: VOK-Get-v${{ env.VERSION }}-Linux-${{ matrix.architecture }}.zip
